###############################################################################################################################
## Author: Amelia Bertozzi-Villa
## Description: Generic plotting code for line plots
##Input: 
##      --data: the data.table generated by dta_to_csv in 00_dta_to_csv.py
## Output:
##      --deaths: a cleaned data.table
##############################################################################################################################

line_plot <- function(data, yvar, facet_str, title, ylabel, xvar="year", groupvar="1",  xlabel="Year"){
  image <- ggplot(data, aes_string(x=xvar, y=yvar, group=groupvar)) +
          geom_line(aes_string(color=groupvar), size=3) +
          facet_grid(as.formula(facet_str)) +
          labs(title=title,
               x=xlabel,
               y=ylabel)
          
  return(image)
}