###############################################################################################################################
## Author: Amelia Bertozzi-Villa
## Description: Generic plotting code for line plots
##Input: 
##      --data: the data.table generated by dta_to_csv in 00_dta_to_csv.py
## Output:
##      --deaths: a cleaned data.table
##############################################################################################################################

##function to get rates and proportions from dataset
sumvars <- function(data, pop, bysum, byprop, byrate, rate_per){
  summed <- data[, list(deaths=sum(deaths)), by=bysum]
  summed[, summed_deaths:= sum(deaths), by=byprop]
  summed[, prop:= ifelse(summed_deaths==0, 0,deaths/summed_deaths)]
  sumpop <- pop[, list(pop=sum(pop)), by=byrate]
  summed <- merge(summed, sumpop, by=intersect(names(summed), names(sumpop)), all=T)
  summed[, rate:=(deaths/pop)*rate_per]
  return(summed)
}

gg_color_hue <- function(n) {
  hues = seq(15, 375, length=n+1)
  hcl(h=hues, l=65, c=100)[1:n]
}

line_plot <- function(data, yvar, facet_str, title, pal="Set2", ylabel, xvar="year", groupvar="1",  xlabel="Year"){
  image <- ggplot(data, aes_string(x=xvar, y=yvar, group=groupvar)) +
          geom_line(aes_string(color=groupvar), size=3) +
          facet_grid(as.formula(facet_str)) +
          labs(title=title,
               x=xlabel,
               y=ylabel)
  if (length(unique(data[[groupvar]]))>8){
    pal<-"Paired"
  }
  if (groupvar!="1"){
    image <- image + scale_color_brewer(palette=pal)
  }else{
    image <- image + guides(color=FALSE)
  }
  
  return(image)
}

bar_plot <- function(data, yvar, fillvar, facet_str, title, pal="Set2", ylabel, xvar="year",  xlabel="Year"){
  image <- ggplot(data, aes_string(x=xvar, y=yvar, fill=fillvar)) +
            geom_bar(stat="identity") +
            facet_grid(as.formula(facet_str)) +
            scale_fill_brewer(palette=pal) +
            labs(title=title,
                 x=xlabel,
                 y=ylabel)
  
  return(image)
}

map_plot <- function(data, fillvar, facet_str, title, colors=brewer.pal(7, "Reds"), limvals=NULL, outline=F){
  image <- ggplot(data) +
            geom_polygon(aes_string(x="long", y="lat", group="group", fill=fillvar)) +
            facet_wrap(as.formula(facet_str)) +
            scale_fill_gradientn(colours=colors, limits=limvals) +
            scale_x_continuous("", breaks=NULL) +
            scale_y_continuous("", breaks=NULL) +
            coord_fixed(ratio=1) +
            guides(fill=guide_colourbar(title="", barheight=20)) +
            labs(title = title) +
            theme_bw(base_size=20)
  
  if (outline==T) image<-image+geom_path(data=data, aes(x=long, y=lat, group=group))
            
  return(image)
            
}  
